### ISSUE TITLE
Build incomplete in mingw32

### ISSUE THREAD

**Issue by eblanca** [xiph/vorbis#15]
I'm building the library in msys + mingw (not the newest mingw-w64) and I set the configure script for building static libs.
Now, the library libvorbisfile.a turns out to be incomplete, because it is built using
`libtool: link: ar cru .libs/libvorbisfile.a  vorbisfile.o`
while it should be instead
`libtool: link: ar cru .libs/libvorbisfile.a  vorbisfile.o synthesis.o`

If we don't do so, later linking of any executables to libvorbisfile.a will fail because the library itself lacks some object (they're coming from synthesis.o).

**Comment by erikd** [comment]
Don't you need to link `libvorbis.a` *and* `libvorbisfile.a` ?

**Comment by eblanca** [comment]
My bad, I just reviewed my 'make' log and I see synthesis.o is part of libvorbis.a
Indeed, when I link both libvorbis.a and libvorbisfile.a, the linker is able to find everything it needs.
Sorry, my build environment was a bit messy yesterday.
