### ISSUE TITLE
Packaging ogg & vorbis with conan

### ISSUE THREAD

**Issue by dimi309** [xiph/vorbis#22]
Hello,

I've been using ogg and vorbis for a while. Recently, I have packaged them with conan, an open source C/C++ package manager and placed the packages on bintray:

https://bintray.com/dimi309/conan-packages/ogg%3Adimi309

https://bintray.com/dimi309/conan-packages/vorbis%3Adimi309

I hope you don't mind :)

The packages are in the process of being evaluated for inclusion into a curated repository on bintray, which is to only contain good quality conan packages. I am writing to ask you if you would be interested in maintaining the packages directly. I can provide you with the packaging code (actually, you can just copy it, since it's open source) or even introduce a pull request with some non-intrusive changes that would allow you to package them directly from the main ogg and vorbis repositories.

**Comment by erikd** [comment]
I don't speak for Xiph, but I am involved in maintaining a Xiph library (FLAC).

> I hope you don't mind :)

As long as you are abiding by the license, I really don't think anyone at Xiph would mind. Quite the contrary. This is open source software. 

> I am writing to ask you if you would be interested in maintaining the packages directly.

Almost certainly not. Bintray serves a similar purpose to Linux distributions. Xiph is not involved with packaging Xiph libraries for the different Linux distributions. Similarly, Xiph is probably not interested in packaging Xiph libraries for Bintray.

**Comment by dimi309** [comment]
I understand. Thank you very much for writing back with this information.

I have read through the license and I will always make sure I abide to it. Nevertheless, since mistakes happen, I will just go ahead and mention that if (now or ever) you or anyone else sees something wrong while having a look at the two above mentioned packages, I would be more than willing to make any required modifications.

One last question that I have, in case someone knows: Would it be ok if I add the xiph logo to the packages? (not to misrepresent them in any way, just to make them more recognisable)

Please feel free to close this request whenever you think that would be appropriate.

**Comment by dimi309** [comment]
For whoever is interested, I have moved the vorbis and ogg conan packages to bincrafters, since it's better to work in a team:

http://bintray.com/bincrafters/public-conan/ogg%3Abincrafters

http://bintray.com/bincrafters/public-conan/vorbis%3Abincrafters
