### ISSUE TITLE
configure is redundant in build instructions

### ISSUE THREAD

**Issue by tzahola** [xiph/vorbis#28]
README.md says you can build vorbis from master like this:
```
./autogen.sh
./configure
make
```
However, `autogen.sh` already runs `configure` at the end:
```
...
$srcdir/configure --enable-maintainer-mode "$@" && echo
```

**Comment by Kaos-Industries** [comment]
This doesn't seem to be true, I had to run configure separately after running autogen.

**Comment by tzahola** [comment]
`autogen.sh` used to look different: https://github.com/xiph/vorbis/commit/4729a15df74cd4d6fc487a43157bf9fb65d12218

This issue seems to be fixed now!
