### ISSUE TITLE
No CMakeLists inside release archive

### ISSUE THREAD

**Issue by NukeBird** [xiph/vorbis#32]
Can you add CMakeLists to release? 

It helps me alot in adding vorbis to [hunter package manager](https://github.com/ruslo/hunter)

**Comment by NukeBird** [comment]
>add FLAC ruslo/hunter#1130
(Ugh. Wrong topic. Comment already deleted)

**Comment by adrianbroher** [comment]
I agree, why is this documented in `CHANGES` but not part of the archive?

**Comment by tdaede** [comment]
The release archives are built with "make distcheck". I would take a patch that adds the appropriate files to EXTRADIST in Makefile.am.
