### ISSUE TITLE
Add vorbis resampler

### ISSUE THREAD

**Issue by calthax** [xiph/vorbis#4]
Making a vorbis resampler just like the speex one will make a better resampler so why aren't we making one

**Comment by erikd** [comment]
Please explain what it is you are suggesting.

**Comment by calthax** [comment]
A vorbis resampler is a resampler that uses vorbis just like the one that uses speex

**Comment by erikd** [comment]
The "speex resampler" does not actually use the Speex audio codec to do the resampling. Instead, the "speex resampler" is an audio codec independent resampler that just happens to be bundled with the Speex codec source code.
