### ISSUE TITLE
free of uninitialized stack variable after seek error

### ISSUE THREAD

**Issue by ianhattendorf** [xiph/vorbis#42]
`work_os` declared: https://github.com/xiph/vorbis/blob/master/lib/vorbisfile.c#L1232
`goto seek_error`: https://github.com/xiph/vorbis/blob/master/lib/vorbisfile.c#L1257
`ogg_stream_init work_os`: https://github.com/xiph/vorbis/blob/master/lib/vorbisfile.c#L1284
`ogg_stream_clear work_os`: https://github.com/xiph/vorbis/blob/master/lib/vorbisfile.c#L1395
`ogg_stream_clear` tries to free data from junk pointer: https://github.com/xiph/ogg/blob/master/src/framing.c#L223

**Comment by sezero** [comment]
This looks like the same issue at https://github.com/SFML/SFML/issues/1241
The following bug entries are open, and a patch was proposed for it:
https://trac.xiph.org/ticket/2327
https://gitlab.xiph.org/xiph/vorbis/issues/2327

Nobody cared about it yet, as it seems.

**Comment by sezero** [comment]
Has anybody reviewed the patch mentioned above?

**Comment by d4ddi0** [comment]
I found a crash bug running Battle for Wesnoth which this patch fixed. The symptom  appears to be a race condition between loading audio and playing it in another thread. I'm not sure why more people haven't seen the issue.  Maybe because I don't use pulseaudio on the machine?

**Comment by d4ddi0** [comment]
Anything playing ogg files through sdl2-mixer could theoretically hit the problem.

**Comment by sezero** [comment]
PING ?

**Comment by d4ddi0** [comment]
I made a PR out of the patch. Hopefully that will get it moving.
https://github.com/xiph/vorbis/pull/53

**Comment by sezero** [comment]
This should be closed after commit 128f0f812b
