### ISSUE TITLE
Enable support for smart/shallow cloning

### ISSUE THREAD

**Issue by Kaos-Industries** [xiph/vorbis#56]
When I do:

`git -C vorbis pull 2> /dev/null || git clone --depth 1 https://git.xiph.org/vorbis.git/`

...I get the following error:

`fatal: dumb http transport does not support shallow capabilities`

This is a huge problem as shallow cloning is the standard nowadays, and Github appears to have officially deprecated dumb cloning almost a decade ago:

https://github.blog/2011-03-09-git-dumb-http-transport-to-be-turned-off-in-90-days/

Is there any chance of this being brought up to date?

**Comment by dm8tbr** [comment]
We are moving away from gitosis to GitLab in the long run.

You should have more success by looking at https://gitlab.xiph.org - which is kept in sync.

https://gitlab.xiph.org/xiph/vorbis in case of Vorbis

**Comment by Kaos-Industries** [comment]
Why doesn't the website make any mention of this? It's has links to both the Github and SVN but not Gitlab.
