### ISSUE TITLE
CMakeLists file not packaged in the libvorbis.tar.gz file 

### ISSUE THREAD

**Issue by martinRenou** [xiph/vorbis#61]
It looks like the `CMakeLists.txt` file is not packaged in the `http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.6.tar.gz` file. But it is needed for building with cmake. Is it not packaged on purpose? Or could it be done?

**Comment by rillian** [comment]
This has been done, but it was after the last release was published. We'll need to do a new release so the cmake build is available. In the meantime, you'll have to build out of git.

**Comment by rillian** [comment]
Closing as a duplicate of #32.

**Comment by martinRenou** [comment]
Oh sorry for the duplicate then! Thank you

**Comment by rillian** [comment]
No problem. It's good to be reminded we need to make another release.
